name: NGINX Security CI

on: [push]

jobs:
  docker_image_scan:
    name: Docker Scout Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1

      - name: Build Docker Image
        run: docker build -f Dockerfile -t mynginx:latest .

      - name: Docker Scout Scan
        uses: docker/scout-action@v1.0.9
        with:
          dockerhub-user: ${{ secrets.REPO_USER }}
          dockerhub-password: ${{ secrets.REPO_PWD }}
          command: quickview,cves
          only-severities: critical,high
          sarif-file: scout-report.sarif

      - name: Upload Docker Scout Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: docker-scout-findings
          path: scout-report.sarif
